# Render deployment configuration
services:
  - type: web
    name: ecommerce-pro-backend
    env: node
    buildCommand: npm install && npm run build:server-only
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # This should be set manually in the Render dashboard
      - key: JWT_SECRET
        sync: false # This should be set manually in the Render dashboard
      - key: SESSION_SECRET
        sync: false # This should be set manually in the Render dashboard
      - key: ALLOWED_ORIGINS
        sync: false # This should be set manually in the Render dashboard
      - key: FRONTEND_URL
        sync: false # This should be set manually in the Render dashboard
      - key: STRIPE_SECRET_KEY
        sync: false # This should be set manually in the Render dashboard
